version: "3"
services:
  frontend:
    build:
      context: ./frontend/pomodoro
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend-nextjs
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    volumes:
      - ./frontend/pomodoro:/usr/src/app
    command: yarn dev
    depends_on:
      - backend
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    container_name: backend-flask
    volumes:
      - ./backend:/usr/src/app
    command: flask run --host=0.0.0.0
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    container_name: survival-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default_authentication_plugin=mysql_native_password
